import img1 from './images/Astronomical-Terms-Definitions.jpg'
function Astronomyterms() {
  
    return (
     <div>
         {/*<h1 className='head'>Astronomy Terms</h1>*/}
         <img src={img1} className='w-100 rounded'></img>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>PLANETS</h2>
                  <p>An astronomical body orbiting a star or stellar remnant.It is massive enough to be rounded by its own gravity.</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>STAR</h2>
                  <p>An astronomical body consisting of a luminous spheroid of plasma held together by its own gravity.</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>SPHEROID</h2>
                  <p>A shape that is generated by rotating an ellipse around one of its axes.</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>PLASMA</h2>
                  <p>A gas that is so hot that some or all its constituent atoms are split up into electrons and ions,which can moce independently of each other.</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>PLANETARY SYSTEM</h2>
                  <p>An set of gravitationally bound non-stellar objects in or out of orbit around a star or star system.</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>STAR SYSTEM</h2>
                  <p>A small number of stars that orbits each other , bound by gravitational attraction.</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>STAR CLUSTER</h2>
                  <p>A large number of stars bound by gravitational attraction. Classified as GLOBULAR CLUSTER and OPEN CLUSTER</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>GLOBULAR CLUSTER</h2>
                  <p>A star cluster consisting stars in range between 10000 to 1000000.</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>OPEN CLUSTER</h2>
                  <p>A star cluster consisting upto few hundred members within a region up to 30 light-years across.</p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>LIGHT YEAR (ly)</h2>
                  <p>The distance travelled by light in vaccum in one julia year ( 365.25 days). 1 ly = 63241.1 AU. </p>
                  </div>
               </div>
         </div>
         <div className="card card-body p-0 m-3  bg-info rounded text-center w-90">
               <div >
                  <div>
                  <h2>ASTRONOMICAL UNIT (AU)</h2>
                  <p>A unit of length effectively equal to the average or mean distance between Earth and the Sun. 1 AU = 149597870.7 Km. </p>
                  </div>
               </div>
         </div>
     </div>
    );
  }
  
  export default Astronomyterms;